---
- name: Create User Account
  user:
    user: "{{ item.user }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default('') }}"
    append: "{{ item.append | default('yes') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ users }}"

- name: Add User Account Authorized Key
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', item.authorized_key) }}"
    state: present
  with_items: "{{ users }}"

- name: Copy User Account Environment
  copy:
    src: .bash_profile
    dest: "/home/{{ item.user }}"
    owner: "{{ item.user }}"
    group: "{{ item.groups.split(',')[0] }}"
    mode: 0700
  with_items: "{{ users }}"

- name: Sudo Admin Successfully
  file:
    path: "/home/{{ item.user }}/.sudo_as_admin_successful"
    state: touch
  with_items: "{{ users }}"
