---
users_add_authorized_key: true
users:
  - user: "{{ ansible_ssh_user }}"
    groups: sudo
    authorized_key: ~/.ssh/id_rsa.pub
  - user: deploy
    groups: www-data,sudo
    authorized_key: ~/.ssh/id_rsa.pub
