---
users:
  - user: "{{ ansible_ssh_user }}"
    groups: sudo
    authorized_key: ~/.ssh/id_rsa.pub
  - user: deploy
    groups: www-data,sudo
    authorized_key: ~/.ssh/id_rsa.pub

server_nfs_enabled: false
server_disable_ssh_password_login: false
server_fix_vm_networking: false
user_account: "{{ ansible_ssh_user }}"
xdebug: false
nginx_path_owner: deploy
nginx_path_group: deploy