---
- name: Uninstall Go
  file:
    path: "{{ go_install_path }}/go"
    state: absent

- name: Install Go
  unarchive:
    src: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: "{{ go_install_path }}"

- name: Set File Permissions
  file:
    path: "{{ go_install_path }}/go"
    owner: root
    group: root
    mode: 755
    recurse: yes

- name: Setup Go Environment
  template:
    src: go.sh.j2
    dest: /etc/profile.d/go.sh
    owner: root
    group: root
    mode: 0644

- name: Make Go Path Directory
  file:
    path: "{{ go_path }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: 744