---
- name: Install Transport HTTPS
  apt:
    name: apt-transport-https
    state: present

- name: Add NodeSource Repository Key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource Node JS Repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: Install NodeJS
  apt:
    name: nodejs
    state: present

- name: Add Yarn Repository Key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    id: "1646B01B86E50310"
    state: present

- name: Add Yarn Repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
    update_cache: yes

- name: Install Yarn
  apt:
    name: yarn
    state: present
