---
- name: Add Nginx PPA
  apt_repository:
    repo: "{{ nginx_ppa }}"

- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Disable Default Site
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

- name: Configure UFW
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items:
    - { rule: allow, port: http }
    - { rule: allow, port: https }

- name: Create Website Directory
  file:
    path: "{{ nginx_path }}"
    state: directory
    owner: deploy
    group: deploy
    mode: 0774
  when: inventory_hostname in groups['production']
